# image will be published to ghcr.io/<user>/<name>
name: netxms-server
# description will be included in the image's metadata
description: Custom server image for NetXMS.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-bootc
image-version: 41

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://packages.netxms.org/fedora/netxms.repo
    install:
      - netxms-server
      - netxms-dbdrv-pgsql

  - type: systemd
    system:
      enabled:
        - netxms-server